// file: RPGOntology.java generated by ontology bean generator.  DO NOT EDIT, UNLESS YOU ARE REALLY SURE WHAT YOU ARE DOING!
package RPG.ontology;

import jade.content.onto.*;
import jade.content.schema.*;

/** file: RPGOntology.java
 * @author ontology bean generator
 * @version 2022/05/28, 19:07:58
 */
public class RPGOntology extends jade.content.onto.Ontology  {

  private static final long serialVersionUID = 4465120161782918442L;

  //NAME
  public static final String ONTOLOGY_NAME = "RPG";
  // The singleton instance of this ontology
  private static Ontology theInstance = new RPGOntology();
  public static Ontology getInstance() {
     return theInstance;
  }


   // VOCABULARY
    public static final String COMBATACTION_ATTACKACTION="AttackAction";
    public static final String COMBATACTION_ACTIONTYPE="ActionType";
    public static final String COMBATACTION="CombatAction";
    public static final String GAMEACTIONRESPONSE_SUCCESS="Success";
    public static final String GAMEACTIONRESPONSE="GameActionResponse";
    public static final String SITUATION_ACTIONS="Actions";
    public static final String SITUATION_PROMPT="Prompt";
    public static final String SITUATION="Situation";
    public static final String REQUESTTOREGISTERDM_MAGICWORD="MagicWord";
    public static final String REQUESTTOREGISTERDM="RequestToRegisterDM";
    public static final String MAP_CONTENT="Content";
    public static final String MAP="Map";
    public static final String DUNGEONMASTERSLISTRESPONSE_DMSLIST="DMsList";
    public static final String DUNGEONMASTERSLISTRESPONSE="DungeonMastersListResponse";
    public static final String FINDDUNGEONMASTERS_DIFFICULTY="Difficulty";
    public static final String FINDDUNGEONMASTERS="FindDungeonMasters";
    public static final String GAMEACTION_WANTTOLEAVE="WantToLeave";
    public static final String GAMEACTION_WANTTOJOIN="WantToJoin";
    public static final String GAMEACTION="GameAction";
    public static final String REGISTERDMRESPONSE_DM="DM";
    public static final String REGISTERDMRESPONSE="RegisterDMResponse";
    public static final String DUNGEONMASTER_DESCRIPTION="Description";
    public static final String DUNGEONMASTER_DIFFICULTY="Difficulty";
    public static final String DUNGEONMASTER_NAME="name";
    public static final String DUNGEONMASTER="DungeonMaster";
    public static final String MOVEACTION_DIRECTION="Direction";
    public static final String MOVEACTION="MoveAction";
    public static final String ATTACK_DAMAGE="Damage";
    public static final String ATTACK_ATTACKNAME="AttackName";
    public static final String ATTACK_ACCURACY="Accuracy";
    public static final String ATTACK_ATTACKDESCRIPTION="AttackDescription";
    public static final String ATTACK="Attack";

  /**
   * Constructor
  */
  private RPGOntology(){ 
    super(ONTOLOGY_NAME, BasicOntology.getInstance());
    try { 

    // adding Concept(s)
    ConceptSchema attackSchema = new ConceptSchema(ATTACK);
    add(attackSchema, RPG.ontology.Attack.class);
    ConceptSchema moveActionSchema = new ConceptSchema(MOVEACTION);
    add(moveActionSchema, RPG.ontology.MoveAction.class);
    ConceptSchema dungeonMasterSchema = new ConceptSchema(DUNGEONMASTER);
    add(dungeonMasterSchema, RPG.ontology.DungeonMaster.class);

    // adding AgentAction(s)

    // adding AID(s)

    // adding Predicate(s)
    PredicateSchema registerDMResponseSchema = new PredicateSchema(REGISTERDMRESPONSE);
    add(registerDMResponseSchema, RPG.ontology.RegisterDMResponse.class);
    PredicateSchema gameActionSchema = new PredicateSchema(GAMEACTION);
    add(gameActionSchema, RPG.ontology.GameAction.class);
    PredicateSchema findDungeonMastersSchema = new PredicateSchema(FINDDUNGEONMASTERS);
    add(findDungeonMastersSchema, RPG.ontology.FindDungeonMasters.class);
    PredicateSchema dungeonMastersListResponseSchema = new PredicateSchema(DUNGEONMASTERSLISTRESPONSE);
    add(dungeonMastersListResponseSchema, RPG.ontology.DungeonMastersListResponse.class);
    PredicateSchema mapSchema = new PredicateSchema(MAP);
    add(mapSchema, RPG.ontology.Map.class);
    PredicateSchema requestToRegisterDMSchema = new PredicateSchema(REQUESTTOREGISTERDM);
    add(requestToRegisterDMSchema, RPG.ontology.RequestToRegisterDM.class);
    PredicateSchema situationSchema = new PredicateSchema(SITUATION);
    add(situationSchema, RPG.ontology.Situation.class);
    PredicateSchema gameActionResponseSchema = new PredicateSchema(GAMEACTIONRESPONSE);
    add(gameActionResponseSchema, RPG.ontology.GameActionResponse.class);
    PredicateSchema combatActionSchema = new PredicateSchema(COMBATACTION);
    add(combatActionSchema, RPG.ontology.CombatAction.class);


    // adding fields
    attackSchema.add(ATTACK_ATTACKDESCRIPTION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    attackSchema.add(ATTACK_ACCURACY, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    attackSchema.add(ATTACK_ATTACKNAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    attackSchema.add(ATTACK_DAMAGE, (TermSchema)getSchema(BasicOntology.INTEGER), ObjectSchema.MANDATORY);
    moveActionSchema.add(MOVEACTION_DIRECTION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    dungeonMasterSchema.add(DUNGEONMASTER_NAME, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    dungeonMasterSchema.add(DUNGEONMASTER_DIFFICULTY, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    dungeonMasterSchema.add(DUNGEONMASTER_DESCRIPTION, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    registerDMResponseSchema.add(REGISTERDMRESPONSE_DM, dungeonMasterSchema, ObjectSchema.MANDATORY);
    gameActionSchema.add(GAMEACTION_WANTTOJOIN, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.MANDATORY);
    gameActionSchema.add(GAMEACTION_WANTTOLEAVE, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.MANDATORY);
    findDungeonMastersSchema.add(FINDDUNGEONMASTERS_DIFFICULTY, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    dungeonMastersListResponseSchema.add(DUNGEONMASTERSLISTRESPONSE_DMSLIST, dungeonMasterSchema, 0, ObjectSchema.UNLIMITED);
    mapSchema.add(MAP_CONTENT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    requestToRegisterDMSchema.add(REQUESTTOREGISTERDM_MAGICWORD, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    situationSchema.add(SITUATION_PROMPT, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.OPTIONAL);
    situationSchema.add(SITUATION_ACTIONS, new ConceptSchema("Concept"), 0, ObjectSchema.UNLIMITED);
    gameActionResponseSchema.add(GAMEACTIONRESPONSE_SUCCESS, (TermSchema)getSchema(BasicOntology.BOOLEAN), ObjectSchema.OPTIONAL);
    combatActionSchema.add(COMBATACTION_ACTIONTYPE, (TermSchema)getSchema(BasicOntology.STRING), ObjectSchema.MANDATORY);
    combatActionSchema.add(COMBATACTION_ATTACKACTION, attackSchema, ObjectSchema.OPTIONAL);

    // adding name mappings

    // adding inheritance

   }catch (java.lang.Exception e) {e.printStackTrace();}
  }
}
